menu:
  Home: /
  Archives: /archives
  About: /about

excerpt_link: Read More

addthis:
  enable: false

fancybox: false

google_analytics:
rss:

cdn2: ""
cdn: http://7xp7jw.com1.z0.glb.clouddn.com/myTheme/static

